import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'overview',
    {
      type: 'category',
      label: 'Introduction',
      items: [{type: 'autogenerated', dirName: 'introduction'}],
    },
    'learning-outcomes',
    'hardware-requirements',
    {
        type: 'category',
        label: 'Assessments',
        items: [{type: 'autogenerated', dirName: 'assessments'}],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [{type: 'autogenerated', dirName: 'module1-ros'}],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [{type: 'autogenerated', dirName: 'module2-simulation'}],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [{type: 'autogenerated', dirName: 'module3-ai'}],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [{type: 'autogenerated', dirName: 'module4-vla'}],
    },
  ],
};

export default sidebars;
